name: PlayVu Backend Pipeline

run-name: Deploy to AWS by @{{ github.actor }}

on: 
  push:
    branches:
    - 'feature/**'

env:
  PROJECT_LOCATION: INSERT_PROJECT_LOCATION_NAME_HERE
  ELASTIC_BEANSTALK_NAME: INSERT_NAME_REFERENCE_HERE
  ELASTIC_BEANSTALK_ENV_NAME: INSERT_BEANSTALK_ENV_NAME_REFERENCE_HERE

jobs:
  checkstyle:
    name: runner / checkstyle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dbelyaev/action-checkstyle@master
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check
          level: warning
  build:
    runs-on: ubuntu-latest

    # Make the jar file

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:

    # deploy to aws